//
//  json.swift
//  kdRemedio
//
//  Created by Hélio Mesquita on 13/09/18.
//  Copyright © 2018 callidus. All rights reserved.
//

import Foundation

let json = """
{
   "ubs":[
      {
         "name":"Cavadas",
         "address":"R Cavadas, 412, Bairro, Guarulhos - SP",
         "google_maps":"https://www.google.com.br",
         "coordinate":{
            "latitude":23.4723751,
            "longitude":46.5474331
         },
         "medicines":[
            {
               "name":"Aspirina",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Dipirona",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Acido",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Paracetamol",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            }
         ]
      },
      {
         "name":"São Rafael",
         "address":"R Domingos de Abreu, 4, Bairro, Guarulhos - SP",
         "google_maps":"https://www.google.com.br",
         "coordinate":{
            "latitude":-23.4705997,
            "longitude":-46.5549484
         },
         "medicines":[
            {
               "name":"Dipirona",
               "available":12,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Paracetamol",
               "available":10,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            }
         ]
      },
      {
         "name":"Jd São Ricardo",
         "address":"R. Sd. Jaír da Silva Taváres, 10, Bairro, Guarulhos - SP",
         "google_maps":"https://www.google.com.br",
         "coordinate":{
            "latitude":-23.465843,
            "longitude":-46.5488985
         },
         "medicines":[
            {
               "name":"Dipirona",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Aspirina",
               "available":60,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            }
         ]
      },
      {
         "name":"Jardim Paravent",
         "address":"R. Vila Lobos, 340, Bairro, Guarulhos - SP",
         "google_maps":"https://www.google.com.br",
         "coordinate":{
            "latitude":-23.4708178,
            "longitude":-46.5445672
         },
         "medicines":[
            {
               "name":"Dipirona",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Nimesulida",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Cafeina",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            }
         ]
      },
      {
         "name":"Vila Fátima",
         "address":"R. Esmeralda, 25, Bairro, Guarulhos - SP",
         "google_maps":"https://www.google.com.br",
         "coordinate":{
            "latitude":-23.481537,
            "longitude":-46.5681197
         },
         "medicines":[
            {
               "name":"Nimesulida",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Maracujina",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            },
            {
               "name":"Tamarim",
               "available":100,
               "links":{
                  "safe":{
                     "url":"https://www.banana.com.br/ubs=id?remedio=id",
                     "method":"POST"
                  }
               }
            }
         ]
      }
   ]
}
"""
