excluded:
- R.generated.swift
- Pods
- Frameworks
- Xibs
- Storyboards
- kdRemedioTests
disabled_rules:
- force_try
- nesting
- block_based_kvo
- class_delegate_protocol
- unused_closure_parameter
- force_cast
- shorthand_operator
- identifier_name
- line_length
- legacy_constructor
- multiple_closures_with_trailing_closure
- function_parameter_count
- type_name
- closure_end_indentation
opt_in_rules:
- empty_count
- explicit_init
- closure_spacing
- overridden_super_call
- redundant_nil_coalescing
- nimble_operator
- first_where
- sorted_imports
- prohibited_super_call
- fatal_error_message
- let_var_whitespace
- extension_access_modifier
- pattern_matching_keywords
- literal_expression_end_indentation
line_length: 120
